language: python

matrix:
  include:
    - python: 3.5
      os: linux
    - python: 3.5
      os: osx
    - python: 3.6
      os: linux
    - python: 3.6
      os: osx
    - python: 3.7
      os: linux
      dist: xenial
      sudo: true
    - python: 3.7
      os: osx

install:
  - pip3 install -r requirements-dev.txt

script:
  - flake8 rtry --max-line-length 99
  - mypy rtry
  - coverage run --source=rtry -m unittest tests

after_success:
  - codecov
