language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
install:
    - pip3 install -r requirements-dev.txt
script:
    - mypy rtry
    - coverage run --source=rtry -m unittest tests
after_success:
    - codecov
