version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements-dev.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            coverage run --source=rtry -m unittest tests
      - run:
          name: upload coverage
          command: |
            . venv/bin/activate
            codecov
