version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python3 -m unittest tests
